import torch
import torch.nn.functional as F
import os
import unittest
from HTMLTestRunner import HTMLTestRunner
from torch.testing._internal.zkp_test_lists import CustomTestCase
# x1 = torch.tensor([[1, 1, 1, 1]], dtype=torch.BLS12_381_Fr_G1_Base)
# x2 =torch.tensor([[2, 1, 1, 1]], dtype=torch.BLS12_381_Fr_G1_Base)

# x3=torch.tensor([[2,1,1,1]],dtype=torch.BLS12_381_Fr_G1_Base)
# custom_data_1 =F.to_mod(x1)
# custom_data_2 =F.to_mod(x2)
# print(F.mul_mod(custom_data_1,custom_data_2))
# print('\n')
# print(F.to_mod(x3))

if __name__ == '__main__':
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(CustomTestCase))

    # with open('HTMLReport.html', 'w') as f:
    #     runner = HTMLTestRunner(stream=f,
    #                             title='MathFunc Test Report',
    #                             description='generated by HTMLTestRunner.',
    #                             verbosity=2
    #                             )
    #     runner.run(suite)

    runner = unittest.TextTestRunner()
    runner.run(suite)
