import torch
import torch.nn.functional as F
import os
import unittest
from HTMLTestRunner import HTMLTestRunner
from torch.testing._internal.zkp_test_lists import CustomTestCase


if __name__ == '__main__':
    suite = unittest.TestSuite()
    suite.addTests(unittest.TestLoader().loadTestsFromTestCase(CustomTestCase))

    # with open('HTMLReport.html', 'w') as f:
    #     runner = HTMLTestRunner(stream=f,
    #                             title='MathFunc Test Report',
    #                             description='generated by HTMLTestRunner.',
    #                             verbosity=2
    #                             )
    #     runner.run(suite)

    runner = unittest.TextTestRunner()
    runner.run(suite)
